---
title: "Data Management for Cancer Research"
output: html_document
---

# About the Authors {-}


These credits are based on our [course contributors table guidelines](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/How-to-give-credits).  
 
&nbsp;
&nbsp;
***In [memory](https://galaxyproject.org/jxtx/) of [James Taylor](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02016-0), who was instrumental in initiating this project.***

&nbsp;

***These are currently from another course ... will update later***

|Credits|Names| 
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor|[Carrie Wright](https://carriewright11.github.io)|
|Content Editors/Reviewers|[Candace Savonen](https://www.cansavvy.com/), [Sarah Wheelan](https://www.hopkinsmedicine.org/profiles/details/sarah-wheelan), [Jeff Leek](https://jtleek.com/)|
|Content Directors| [Jeff Leek](https://jtleek.com/), [Sarah Wheelan](https://www.hopkinsmedicine.org/profiles/details/sarah-wheelan)|
|Content Consultants ([Promoting diversity equity and inclusion](https://jhudatascience.org/ITCR_Cancer_Research_Leadership/promoting-diversity-equity-and-inclusion.html))| [Simone Sawyer](https://www.linkedin.com/in/simone-sawyer-msph-1a3b81110/), [Karriem Watson](https://www.linkedin.com/in/karriem-watson-10361035/)|
|Acknowledgments |[Andrei Kucharavy](https://twitter.com/andrei_chiffa/status/1375449259831595008?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1375449259831595008%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=http%3A%2F%2F127.0.0.1%3A4015%2Fabout-the-authors.html), [Sarah Opitz](https://twitter.com/sl_opitz/status/1375385114859933696?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1375385114859933696%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=http%3A%2F%2F127.0.0.1%3A4015%2Fabout-the-authors.html), [Florian Markowetz](https://twitter.com/markowetzlab/status/1374795012173656064?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1374795012173656064%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=http%3A%2F%2F127.0.0.1%3A4015%2Fabout-the-authors.html), [Brody Foy](https://twitter.com/foy_brody/status/1374799432445739010?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1374799432445739010%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=http%3A%2F%2F127.0.0.1%3A4015%2Fabout-the-authors.html), [Michael Mullarkey](https://twitter.com/mcmullarkey/status/1374838375031656456?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1374838375031656456%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=https%3A%2F%2Fpublish.twitter.com%2F%3Fquery%3Dhttps3A2F2Ftwitter.com2Fmcmullarkey2Fstatus2F1374838375031656456widget%3DTweet), [Anne Carpenter](https://twitter.com/DrAnneCarpenter/status/1375383099782139907?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1375383099782139907%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=https%3A%2F%2Fpublish.twitter.com%2F%3Fquery%3Dhttps3A2F2Ftwitter.com2FDrAnneCarpenter2Fstatus2F1375383099782139907widget%3DTweet), [Luis Pedro Coelho](https://twitter.com/luispedrocoelho/status/1375386159480721412?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1375386159480721412%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=https%3A%2F%2Fpublish.twitter.com%2F%3Fquery%3Dhttps3A2F2Ftwitter.com2Fluispedrocoelho2Fstatus2F1375386159480721412widget%3DTweet), [Keri Martinowich](https://twitter.com/martinowk/status/1374803835940528128?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1374803835940528128%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=https%3A%2F%2Fpublish.twitter.com%2F%3Fquery%3Dhttps3A2F2Ftwitter.com2Fmartinowk2Fstatus2F1374803835940528128widget%3DTweet) |
|**Production**||
|Content Publisher|[Ira Gooding](https://publichealth.jhu.edu/faculty/4130/ira-gooding)|
|Content Publishing Reviewers|[Ira Gooding](https://publichealth.jhu.edu/faculty/4130/ira-gooding), [Candace Savonen](https://www.cansavvy.com/)|
|**Technical**||
|Course Publishing Engineer|[Carrie Wright](https://carriewright11.github.io/)|
|Template Publishing Engineers|[Candace Savonen](https://www.cansavvy.com/), [Carrie Wright](https://carriewright11.github.io/)|
|Publishing Maintenance Engineer|[Candace Savonen](https://www.cansavvy.com/)|
|Technical Publishing Stylists|[Carrie Wright](https://carriewright11.github.io/), [Candace Savonen](https://www.cansavvy.com/)|
|Package Developers ([Leanbuild](https://github.com/jhudsl/leanbuild))|[John Muschelli](https://johnmuschelli.com/), [Candace Savonen](https://www.cansavvy.com/), [Carrie Wright](https://carriewright11.github.io/)|
|**Art and Design**||
|Illustrator|[Carrie Wright](https://carriewright11.github.io)|
|**Funding**||
|Funder|[National Cancer Institute (NCI)](https://www.cancer.gov/) UE5 CA254170|
|Funding Staff| Emily Voeglein, Fallon Bachman|

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```
